eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
server:
    port: 0
spring:
    application:
        name: inventory-service
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: mysql
        url: jdbc:mysql://localhost:3306/inventory-service
        username: root
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true